version: '2'

services:
  drupal:
    build: ./docker/drupal
    image: xdebug-web
    ports:
      - "80:80"
      - "443:443"
      - "8022:22"
    expose:
      - "9000"  
    volumes:
      - ./www:/var/www/html/
      - "./docker/drupal/php.ini:/usr/local/etc/php/php.ini"
    privileged: true
    links:
      - db

  db:
    image: mysql:5.6.35
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=test123
